sign in route
GSG-G9/beauty-salon pull request #55
Opened 2021-03-29 10:11 UTC by yasmeenattallah

Fix #20

- [ ] initalize files for sign in Route 
- [ ] make a database query 
- [ ] import query in controller function file 
- [ ] check if the user already sign in

2021-03-29 13:54 UTC, AdhamHaisami commented on server/routes/index.js
>  const router = express.Router();
this line must be the second line I guess

2021-03-29 13:54 UTC, AdhamHaisami reviewed
There are no new lines at the end of files

2021-03-30 12:45 UTC, imansedky5 submitted a review, later dismissed

2021-03-30 19:03 UTC, imansedky5 submitted a review, later dismissed

2021-03-30 21:10 UTC, AdhamHaisami approved these changes

2021-03-30 22:42 UTC, mFlaifel requested changes

2021-03-30 22:42 UTC, mFlaifel commented on server/middleware/validation/signinValidation.js
> +module.exports = signinValidation;
you are doing create job here, but I need you to stick to your teammate file structure and make validation in the utils folder, not as middleware.

2021-03-31 07:53 UTC, imansedky5 approved these changes

2021-03-31 08:01 UTC, merged