contact-us route backend
GSG-G9/beauty-salon pull request #56
Opened 2021-03-29 11:47 UTC by imansedky5

fix #33 

- added new rule   `object-curly-newline` in **.eslintrc.json**
- changed boomify parameter name from **errorMessage** into **message** in b**oomify.js**
- created contact-us route
- created validation schema (**contactusValidation**) for contact-us route

2021-03-30 23:28 UTC, mFlaifel commented on server/controller/user/contactus.js
> +    try {
don't use try-catch block inside another try-catch block

2021-03-30 23:31 UTC, mFlaifel approved these changes
'contactUs' is a common route so move it to the common folder

2021-03-31 09:03 UTC, yasmeenattallah commented on server/controller/common/contactus.js
> +    //   email,
delete commented line

2021-04-01 15:19 UTC, AdhamHaisami submitted a review, later dismissed

2021-04-01 18:42 UTC, mFlaifel commented on server/controller/common/contactus.js
> +      message: 'message sent succesfully',
pay attention to typos
```suggestion
      message: 'message sent successfully,
```

2021-04-01 18:43 UTC, mFlaifel commented on __test__/contactus.test.js
> +    expect(message).toBe('message sent succesfully');
```suggestion
    expect(message).toBe('message sent successfully');
```

2021-04-01 18:47 UTC, mFlaifel requested changes
in the database we have created_at filed 
```SQL
CREATE TABLE contacts (
  "created_at" timestamp, 
);
```
you have to insert a date into it or give it  a default value
```
"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
```

2021-04-02 13:38 UTC, imansedky5 commented
> in the database we have created_at filed
> 
> ```sql
> CREATE TABLE contacts (
>   "created_at" timestamp, 
> );
> ```
> 
> you have to insert a date into it or give it a default value
> 
> ```
> "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
> ```

done

2021-04-02 20:01 UTC, mFlaifel requested changes
please solve the conflict and commented test

2021-04-02 22:06 UTC, imansedky5 commented
> in the database we have created_at filed
> 
> ```sql
> CREATE TABLE contacts (
>   "created_at" timestamp, 
> );
> ```
> 
> you have to insert a date into it or give it a default value
> 
> ```
> "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
> ```

2021-04-03 17:25 UTC, yasmeenattallah submitted a review, later dismissed

2021-04-03 18:30 UTC, merged