Get/getBlogs Route
GSG-G9/beauty-salon pull request #59
Opened 2021-03-29 17:19 UTC by AdhamHaisami

Fix #31 

# Project setup
### Build :
 - blog route
 - controller
 - DB query 
 -  Test them using jest

2021-04-01 19:24 UTC, mFlaifel commented on __test__/getBlogs.test.js
> +  });
suggestion, you can delete this line because we use `--runInBand` flag in the test script to solve this problem

2021-04-01 19:25 UTC, mFlaifel commented on __test__/getBlogs.test.js
> +    test('Expect to return object with statusCode 200 and array of blogs ojects', async () => {
typos detected
```suggestion
    test('Expect to return object with statusCode 200 and array of blogs objects', async () => {
```

2021-04-01 20:07 UTC, mFlaifel commented on server/controller/common/getBlogs.js
> +      throw boomify(500, 'Internal Server Error');
- I think when there is no blog the message will be `no blogs` not `internal server error`
- For the status code, I think `204` no content is acceptable

2021-04-01 20:09 UTC, mFlaifel requested changes
good work

2021-04-03 17:28 UTC, yasmeenattallah submitted a review, later dismissed

2021-04-03 17:40 UTC, imansedky5 commented on server/controller/common/getBlogs.js
> +      throw boomify(203, 'There is no blogs');
i think 203 status is not suitable for your case as it means 203 means **`Non-Authoritative Information (or, "The server successfully processed the request, but is returning information that may be from another source")`**
so you should either use **`204 no content`** as Mohammed mentioned  [here](https://github.com/GSG-G9/beauty-salon/pull/59#discussion_r605916212) or **`200 status`** if you want send a message "no blogs"

2021-04-03 19:18 UTC, merged