text field component
GSG-G9/beauty-salon pull request #67
Opened 2021-03-31 21:08 UTC by yasmeenattallah

Fix #11

2021-04-01 22:44 UTC, mFlaifel commented on client/src/component/inputText/style.js
> +export default useStyles;
take a look at customized [text field in the material ui](https://material-ui.com/components/text-fields/#customized-inputs)

2021-04-01 22:47 UTC, mFlaifel commented on client/src/component/inputText/index.js
> +      type="text"
these lines are not needed, as the variant is default to `outlined` in our general theme, and the type may be changed according to the form like `password, email, ...`

2021-04-01 22:48 UTC, mFlaifel requested changes
- don't forget to export the file to component/index.js

2021-04-07 07:35 UTC, imansedky5 approved these changes

2021-04-07 07:38 UTC, khamis-hesham submitted a review, later dismissed

2021-04-07 08:15 UTC, khamis-hesham approved these changes

2021-04-07 08:32 UTC, imansedky5 approved these changes

2021-04-07 08:42 UTC, AdhamHaisami approved these changes

2021-04-07 08:42 UTC, merged