Home Page
GSG-G9/beauty-salon pull request #93
Opened 2021-04-08 14:29 UTC by AdhamHaisami

Fix #2

# Front-end

 -  Building the Home Page. 
 - Create style.js file.
 - Add landingBackground pic to the assets folder

2021-04-13 22:21 UTC, mFlaifel commented on client/src/pages/Home/index.js
> +              color="contained"
button in material UI don't have property color
please remove this line because it shows an error in the console.
![Uploading image.png…]()

2021-04-13 22:21 UTC, mFlaifel commented on client/src/pages/Home/index.js
> +import { Button } from '@material-ui/core';
please use our custom button

2021-04-13 22:27 UTC, mFlaifel commented on client/src/pages/Home/index.js
> +          ))}
- when rendering a list of data you have to use a key to make react aware of rendering it
![image](https://user-images.githubusercontent.com/32321796/114628854-41693580-9cc0-11eb-9799-42fa81b034f5.png)
[using key in react](https://reactjs.org/docs/lists-and-keys.html#keys)
- you can use javascript destructure

2021-04-13 22:30 UTC, mFlaifel requested changes
mobile UI needs improvement
- there is a lot of empty spaces between section.
- blog section is broken.

![image](https://user-images.githubusercontent.com/32321796/114629179-cb190300-9cc0-11eb-83ca-e25af7293f94.png)

2021-04-13 23:15 UTC, AdhamHaisami commented
> mobile UI needs improvement
> 
> * there is a lot of empty spaces between section.
> * blog section is broken.
> 
> ![image](https://user-images.githubusercontent.com/32321796/114629179-cb190300-9cc0-11eb-83ca-e25af7293f94.png)

I modified the blogs Card to render elements vertically and it works well locally on mobile

2021-04-15 02:46 UTC, mFlaifel commented on client/src/component/header/style.js
> +      // width: '22em',
remove this line

2021-04-15 02:46 UTC, mFlaifel commented on client/src/component/header/style.js
> +      // width: '15em',
remove this line

2021-04-15 02:48 UTC, mFlaifel commented on client/src/component/BlogCard/style.js
>        transform: 'scale(1.1)',
remove hover effects on show more link

2021-04-15 03:22 UTC, merged